services:
  pipeline_worker:
    build:
      context: ./pipeline_worker
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped